# vim ft=yaml
# CI on Windows via appveyor
# Largely from:
# https://github.com/MacPython/cython-wheels/blob/master/appveyor.yml

environment:
  global:
    REPO_DIR: udon2
    PACKAGE_NAME: udon2
    BUILD_COMMIT: v0.1.0
    OTHER_BUILD_DEP: "six svgling"
    OTHER_TEST_DEP: "six svgling"

  matrix:
    # - PYTHON: C:\Python36
    #   PYTHON_ARCH: "32"
    #   BOOST_DIR: C:\Libraries\boost_1_69_0
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    # - PYTHON: C:\Python36-x64
    #   PYTHON_ARCH: "64"
    #   BOOST_DIR: C:\Libraries\boost_1_69_0
    #   APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PYTHON: C:\Python37
      PYTHON_ARCH: "32"
      BOOST_DIR: C:\Libraries\boost_1_69_0
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PYTHON: C:\Python37-x64
      PYTHON_ARCH: "64"
      BOOST_DIR: C:\Libraries\boost_1_69_0
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - PYTHON: C:\Python38
      PYTHON_ARCH: "32"
      BOOST_DIR: C:\Libraries\boost_1_73_0
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PYTHON: C:\Python38-x64
      PYTHON_ARCH: "64"
      BOOST_DIR: C:\Libraries\boost_1_73_0
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    - PYTHON: C:\Python39
      PYTHON_ARCH: "32"
      BOOST_DIR: C:\Libraries\boost_1_77_0
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022
    - PYTHON: C:\Python39-x64
      PYTHON_ARCH: "64"
      BOOST_DIR: C:\Libraries\boost_1_77_0
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2022

install:
  # Fetch submodules
  - git submodule update --init --recursive

  # Install new Python if necessary
  - ps: .\multibuild\install_python.ps1

  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install -U pip setuptools

  # Fix MSVC builds for 64-bit Python. See:
  # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

  # Check that we have the expected version and architecture for Python
  - python --version
  - python -c "import struct; print(struct.calcsize('P') * 8)"

build_script:
  # Install the dependencies of the project.
  - python -m pip install %OTHER_BUILD_DEP%
  # Build wheel
  - python -m pip install -U wheel
  - cd %REPO_DIR%
  - git checkout %BUILD_COMMIT%
  - python setup.py bdist_wheel
  - python -m pip install -U pefile machomachomangler
  - python tools/winauditwheel.py -p udon2 -v 0.1.0
  - cd ..

artifacts:
  - path: "%REPO_DIR%\\dist\\*"

deploy:
  release: $(BUILD_COMMIT)
  description: 'UDon2 $(BUILD_COMMIT)'
  provider: GitHub
  auth_token:
    secure: cf+FtMGNTeiNabWFD6csR9uBNgO5TSgU9/L40BF6/pXRLlnnfxWWM92LmU6ijZ2a
  artifact: dist/*.whl
  draft: false
  prerelease: true
  on:
    branch: master
    APPVEYOR_REPO_TAG: true          # deploy on tag push only